ALTER TABLE users
    ADD is_admin bool DEFAULT FALSE;

CREATE TABLE USER_DELETE_REQUESTS
(
    ID          BIGSERIAL PRIMARY KEY,
    USER_ID     BIGSERIAL                                          NOT NULL REFERENCES USERS (ID),
    IS_APPROVED BOOLEAN,
    CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
